export interface OptionType {
  value: string;
  label: string;
}

export const techSkills: OptionType[] = [
  { value: "JavaScript", label: "JavaScript" },
  { value: "HTML", label: "HTML" },
  { value: "CSS", label: "CSS" },
  { value: "React", label: "React" },
  { value: "Node.js", label: "Node.js" },
  { value: "Express.js", label: "Express.js" },
  { value: "MongoDB", label: "MongoDB" },
  { value: "SQL", label: "SQL" },
  { value: "Python", label: "Python" },
  { value: "Java", label: "Java" },
  { value: "C++", label: "C++" },
  { value: "C#", label: "C#" },
  { value: "Ruby", label: "Ruby" },
  { value: "TypeScript", label: "TypeScript" },
  { value: "Angular", label: "Angular" },
  { value: "Vue", label: "Vue" },
  { value: "Django", label: "Django" },
  { value: "Flask", label: "Flask" },
  { value: "Spring", label: "Spring" },
  { value: "Hibernate", label: "Hibernate" },
  { value: "JPA", label: "JPA" },
  { value: "JDBC", label: "JDBC" },
  { value: "PostgreSQL", label: "PostgreSQL" },
  { value: "MySQL", label: "MySQL" },
  { value: "SQLite", label: "SQLite" },
  { value: "Oracle", label: "Oracle" },
  { value: "SQL Server", label: "SQL Server" },
  { value: "Mongoose", label: "Mongoose" },
  { value: "Sequelize", label: "Sequelize" },
  { value: "Mocha", label: "Mocha" },
  { value: "Chai", label: "Chai" },
  { value: "Jest", label: "Jest" },
  { value: "Cypress", label: "Cypress" },
  { value: "Jasmine", label: "Jasmine" },
  { value: "Karma", label: "Karma" },
];

export const softSkills: OptionType[] = [
  { value: "Communication", label: "Communication" },
  { value: "Teamwork", label: "Teamwork" },
  { value: "Adaptability", label: "Adaptability" },
  { value: "Problem-Solving", label: "Problem-Solving" },
  { value: "Creativity", label: "Creativity" },
  { value: "Work Ethic", label: "Work Ethic" },
  { value: "Interpersonal Skills", label: "Interpersonal Skills" },
  { value: "Time Management", label: "Time Management" },
  { value: "Leadership", label: "Leadership" },
  { value: "Attention to Detail", label: "Attention to Detail" },
  { value: "Organization", label: "Organization" },
  { value: "Critical Thinking", label: "Critical Thinking" },
  { value: "Conflict Resolution", label: "Conflict Resolution" },
  { value: "Decision Making", label: "Decision Making" },
  { value: "Emotional Intelligence", label: "Emotional Intelligence" },
  { value: "Flexibility", label: "Flexibility" },
  { value: "Negotiation", label: "Negotiation" },
  { value: "Persuasion", label: "Persuasion" },
  { value: "Resilience", label: "Resilience" },
  { value: "Stress Management", label: "Stress Management" },
  { value: "Work-Life Balance", label: "Work-Life Balance" },
  { value: "Empathy", label: "Empathy" },
  { value: "Patience", label: "Patience" },
  { value: "Tolerance", label: "Tolerance" },
  { value: "Assertiveness", label: "Assertiveness" },
  { value: "Self-Motivation", label: "Self-Motivation" },
  { value: "Self-Confidence", label: "Self-Confidence" },
  { value: "Self-Discipline", label: "Self-Discipline" },
  { value: "Self-Awareness", label: "Self-Awareness" },
  { value: "Self-Regulation", label: "Self-Regulation" },
];
