import { OptionType } from "../skills/techSkills";

export const softSkills: OptionType[] = [
  { value: "Communication", label: "Communication" },
  { value: "Teamwork", label: "Teamwork" },
  { value: "Adaptability", label: "Adaptability" },
  { value: "Problem-Solving", label: "Problem-Solving" },
  { value: "Creativity", label: "Creativity" },
  { value: "Work Ethic", label: "Work Ethic" },
  { value: "Interpersonal Skills", label: "Interpersonal Skills" },
  { value: "Time Management", label: "Time Management" },
  { value: "Leadership", label: "Leadership" },
  { value: "Attention to Detail", label: "Attention to Detail" },
  { value: "Organization", label: "Organization" },
  { value: "Critical Thinking", label: "Critical Thinking" },
  { value: "Conflict Resolution", label: "Conflict Resolution" },
  { value: "Decision Making", label: "Decision Making" },
  { value: "Emotional Intelligence", label: "Emotional Intelligence" },
  { value: "Flexibility", label: "Flexibility" },
  { value: "Negotiation", label: "Negotiation" },
  { value: "Persuasion", label: "Persuasion" },
  { value: "Resilience", label: "Resilience" },
  { value: "Stress Management", label: "Stress Management" },
  { value: "Work-Life Balance", label: "Work-Life Balance" },
  { value: "Empathy", label: "Empathy" },
  { value: "Patience", label: "Patience" },
  { value: "Tolerance", label: "Tolerance" },
  { value: "Assertiveness", label: "Assertiveness" },
  { value: "Self-Motivation", label: "Self-Motivation" },
  { value: "Self-Confidence", label: "Self-Confidence" },
  { value: "Self-Discipline", label: "Self-Discipline" },
  { value: "Self-Awareness", label: "Self-Awareness" },
  { value: "Self-Regulation", label: "Self-Regulation" },
];
